# Problem-1

Write a function so that the columns of the output matrix are powers of the input vector.

The order of the powers is determined by the increasing boolean argument. Specifically, when
increasing is False, the i-th output column is the input vector raised element-wise to the power of N - i - 1.

HINT: Such a matrix with a geometric progression in each row is named for Alexandre-
Theophile Vandermonde.

In [2]:
import numpy as np

In [11]:
def powers_of_input_matrix(array,size):
    output_matrix=np.column_stack([array**(size-i-1) for i in range(size)])
    print("output_matrix after getting powers of elements in input matrix is \n",output_matrix ) 

array = np.array([3,5,7,8,9])
size=5
powers_of_input_matrix(array,size)

output_matrix after getting powers of elements in input matrix is 
 [[  81   27    9    3    1]
 [ 625  125   25    5    1]
 [2401  343   49    7    1]
 [4096  512   64    8    1]
 [6561  729   81    9    1]]


# Problem-2

Problem Statement 2:

Given a sequence of n values x1, x2, ..., xn and a window size k>0, the k-th moving average of
the given sequence is defined as follows:

The moving average sequence has n-k+1 elements as shown below.
The moving averages with k=4 of a ten-value sequence (n=10) is shown below
i 1 2 3 4 5 6 7 8 9 10
===== == == == == == == == == == ==

Input 10 20 30 40 50 60 70 80 90 100

y1 25 = (10+20+30+40)/4
y2 35 = (20+30+40+50)/4
y3 45 = (30+40+50+60)/4
y4 55 = (40+50+60+70)/4
y5 65 = (50+60+70+80)/4
y6 75 = (60+70+80+90)/4
y7 85 = (70+80+90+100)/4

Thus, the moving average sequence has n-k+1=10-4+1=7 values.

In [22]:
#Creating Function
def moving_avaerage(a,n=3):
    asum=np.cumsum(a,dtype=float)
    asum[n:]=asum[n:]-asum[:-n]
    return asum[n-1:]/n

In [23]:
#Testing for Sample input
a=[10,20,30,40,50,60,70,80,90,100]
a1=np.array(a)
np.array(moving_avaerage(a1,n=4)).round(2)

array([25., 35., 45., 55., 65., 75., 85.])

In [24]:
#Executing for given array
a=[3,5,7,2,8,10,11,65,72,81,99,100,150]
a1=np.array(a)
np.array(moving_avaerage(a1,n=3)).round(2)

array([  5.  ,   4.67,   5.67,   6.67,   9.67,  28.67,  49.33,  72.67,
        84.  ,  93.33, 116.33])